name = "Berbera"
license = "GPL-3.0"
description = "A bootstrap 4 Hugo theme for notes."
tags = ["bootstrap", "blog", "font awesome"]
features = ["responsive", "blog"]
min_version = 0.25

[author]
  name = "Hampus Sandén"
  homepage = "https://hampussanden.com"

[original]
  author = "mdo"
  homepage = "https://v4-alpha.getbootstrap.com/examples/blog/"
